GET http://localhost:5000/localhost:5000/

####

POST http://localhost:5000/api/signup
content-type: application/json

{
   "firstName": "jad",
   "lastName": "jadi",
   "email": "jad@gmail.com",
   "password": "1234"
}

####

POST http://localhost:5000/api/signin
content-type: application/json

{

   "email": "jad@gmail.com",
   "password": "1234"
}